Repository TYPO3-Solr/ext-solr, pull requests merged in 2020-12, with the labels that each got.

#2360 [BUGFIX] Initialize TSFE, if conf of page was cached
  Classes/Util.php
  Tests/Unit/UtilTest.php
Labels: needs feedback

#2814 [TASK] Change configuration files to TYPO3 file extensions
  Configuration/TSconfig/ContentElementWizard.typoscript
  Configuration/TSconfig/Page/Mod/Wizards/NewContentElement.tsconfig
  Configuration/TypoScript/BootstrapCss/setup.txt
  Configuration/TypoScript/BootstrapCss/setup.typoscript
  Configuration/TypoScript/Examples/Ajaxify/setup.txt
  Configuration/TypoScript/Examples/Ajaxify/setup.typoscript
  Configuration/TypoScript/Examples/BoostQueries/setup.txt
  Configuration/TypoScript/Examples/BoostQueries/setup.typoscript
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.typoscript
  Configuration/TypoScript/Examples/EverythingOn/setup.txt
  Configuration/TypoScript/Examples/EverythingOn/setup.typoscript
  Configuration/TypoScript/Examples/Facets/DateRange/setup.txt
  Configuration/TypoScript/Examples/Facets/DateRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.txt
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.typoscript
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.txt
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Options/setup.txt
  Configuration/TypoScript/Examples/Facets/Options/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.typoscript
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.txt
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.typoscript
  Configuration/TypoScript/Examples/FilterPages/setup.txt
  Configuration/TypoScript/Examples/FilterPages/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.typoscript
  Configuration/TypoScript/Examples/Suggest/setup.txt
  Configuration/TypoScript/Examples/Suggest/setup.typoscript
  Configuration/TypoScript/OpenSearch/constants.txt
  Configuration/TypoScript/OpenSearch/constants.typoscript
  Configuration/TypoScript/OpenSearch/setup.txt
  Configuration/TypoScript/OpenSearch/setup.typoscript
  Configuration/TypoScript/Solr/constants.txt
  Configuration/TypoScript/Solr/constants.typoscript
  Configuration/TypoScript/Solr/setup.txt
  Configuration/TypoScript/Solr/setup.typoscript
  Configuration/TypoScript/StyleSheets/setup.txt
  Configuration/TypoScript/StyleSheets/setup.typoscript
  Documentation/Frontend/Facets.rst
  ext_localconf.php
Labels: BACKPORTABLE, Complexity: no brainer

#2815 [TASK:BACKPORT:11] Change configuration files to TYPO3 file extensions
  Configuration/TSconfig/ContentElementWizard.typoscript
  Configuration/TSconfig/Page/Mod/Wizards/NewContentElement.tsconfig
  Configuration/TypoScript/BootstrapCss/setup.txt
  Configuration/TypoScript/BootstrapCss/setup.typoscript
  Configuration/TypoScript/Examples/Ajaxify/setup.txt
  Configuration/TypoScript/Examples/Ajaxify/setup.typoscript
  Configuration/TypoScript/Examples/BoostQueries/setup.txt
  Configuration/TypoScript/Examples/BoostQueries/setup.typoscript
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.typoscript
  Configuration/TypoScript/Examples/EverythingOn/setup.txt
  Configuration/TypoScript/Examples/EverythingOn/setup.typoscript
  Configuration/TypoScript/Examples/Facets/DateRange/setup.txt
  Configuration/TypoScript/Examples/Facets/DateRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.txt
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.typoscript
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.txt
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Options/setup.txt
  Configuration/TypoScript/Examples/Facets/Options/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.typoscript
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.txt
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.typoscript
  Configuration/TypoScript/Examples/FilterPages/setup.txt
  Configuration/TypoScript/Examples/FilterPages/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.typoscript
  Configuration/TypoScript/Examples/Suggest/setup.txt
  Configuration/TypoScript/Examples/Suggest/setup.typoscript
  Configuration/TypoScript/OpenSearch/constants.txt
  Configuration/TypoScript/OpenSearch/constants.typoscript
  Configuration/TypoScript/OpenSearch/setup.txt
  Configuration/TypoScript/OpenSearch/setup.typoscript
  Configuration/TypoScript/Solr/constants.txt
  Configuration/TypoScript/Solr/constants.typoscript
  Configuration/TypoScript/Solr/setup.txt
  Configuration/TypoScript/Solr/setup.typoscript
  Configuration/TypoScript/StyleSheets/setup.txt
  Configuration/TypoScript/StyleSheets/setup.typoscript
  Documentation/Frontend/Facets.rst
  ext_localconf.php
Labels: 10LTS

#2816 [TASK:BACKPORT:10] Change configuration files to TYPO3 file extensions
  Configuration/TSconfig/ContentElementWizard.typoscript
  Configuration/TSconfig/Page/Mod/Wizards/NewContentElement.tsconfig
  Configuration/TypoScript/BootstrapCss/setup.txt
  Configuration/TypoScript/BootstrapCss/setup.typoscript
  Configuration/TypoScript/Examples/Ajaxify/setup.txt
  Configuration/TypoScript/Examples/Ajaxify/setup.typoscript
  Configuration/TypoScript/Examples/BoostQueries/setup.txt
  Configuration/TypoScript/Examples/BoostQueries/setup.typoscript
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt
  Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.typoscript
  Configuration/TypoScript/Examples/EverythingOn/setup.txt
  Configuration/TypoScript/Examples/EverythingOn/setup.typoscript
  Configuration/TypoScript/Examples/Facets/DateRange/setup.txt
  Configuration/TypoScript/Examples/Facets/DateRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.txt
  Configuration/TypoScript/Examples/Facets/Hierarchy/setup.typoscript
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.txt
  Configuration/TypoScript/Examples/Facets/NumericRange/setup.typoscript
  Configuration/TypoScript/Examples/Facets/Options/setup.txt
  Configuration/TypoScript/Examples/Facets/Options/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.typoscript
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.txt
  Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.typoscript
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.txt
  Configuration/TypoScript/Examples/Facets/QueryGroup/setup.typoscript
  Configuration/TypoScript/Examples/FilterPages/setup.txt
  Configuration/TypoScript/Examples/FilterPages/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.txt
  Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.typoscript
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.txt
  Configuration/TypoScript/Examples/IndexQueueTtNews/setup.typoscript
  Configuration/TypoScript/Examples/Suggest/setup.txt
  Configuration/TypoScript/Examples/Suggest/setup.typoscript
  Configuration/TypoScript/OpenSearch/constants.txt
  Configuration/TypoScript/OpenSearch/constants.typoscript
  Configuration/TypoScript/OpenSearch/setup.txt
  Configuration/TypoScript/OpenSearch/setup.typoscript
  Configuration/TypoScript/Solr/constants.txt
  Configuration/TypoScript/Solr/constants.typoscript
  Configuration/TypoScript/Solr/setup.txt
  Configuration/TypoScript/Solr/setup.typoscript
  Configuration/TypoScript/StyleSheets/setup.txt
  Configuration/TypoScript/StyleSheets/setup.typoscript
  Documentation/Frontend/Facets.rst
  ext_localconf.php
Labels: 9LTS

#2806 [BUGFIX] Use rawurldecode on facets to handle (replace #1657)
  Classes/Query/Modifier/Faceting.php
  Tests/Unit/Query/Modifier/FacetingTest.php
Labels: bug
