Repository TYPO3-Solr/ext-solr, pull requests merged in 2020-09, with the labels that each got.

#2695 [BUGFIX] Restricted pages are not being indexed in Typo3 10
  Classes/IndexQueue/FrontendHelper/AbstractFrontendHelper.php
  Classes/IndexQueue/FrontendHelper/Dispatcher.php
  Classes/IndexQueue/FrontendHelper/Manager.php
  Classes/IndexQueue/FrontendHelper/PageIndexer.php
  Classes/IndexQueue/PageIndexerRequestHandler.php
  Classes/Middleware/FrontendUserAuthenticator.php
  Classes/Middleware/PageIndexerFinisher.php
  Classes/Middleware/PageIndexerInitialization.php
  Configuration/RequestMiddlewares.php
  Tests/Integration/Controller/SearchControllerTest.php
  Tests/Integration/Controller/SuggestControllerTest.php
Labels: BACKPORTABLE

#2732 [BUGFIX] Hard codes plugin namespace #2691
  Classes/ViewHelpers/SearchFormViewHelper.php
Labels: BACKPORTABLE, bug

#2678 Fix path of suggest in typoscript settings
  Configuration/TypoScript/Examples/Suggest/setup.txt
  Documentation/Frontend/Autosuggest.rst
Labels: needs changes
