Repository TYPO3-Solr/ext-solr, pull requests merged in 2021-03, with the labels that each got.

#2864 [BUGFIX] Change filter for workspace
  Classes/IndexQueue/Initializer/AbstractInitializer.php
Labels: BACKPORTABLE

#2866 [BUGFIX:BP:11] Change filter for workspace
  Classes/IndexQueue/Initializer/AbstractInitializer.php
Labels: 10LTS, 9LTS

#2791 [TASK] Upgrade to Solarium 6
  Classes/Domain/Search/Query/AbstractQueryBuilder.php
  Classes/Domain/Search/Query/ParameterBuilder/Highlighting.php
  Classes/Domain/Search/Query/QueryBuilder.php
  Classes/Domain/Site/SiteRepository.php
  Classes/System/Solr/Document/Document.php
  Classes/System/Solr/Node.php
  Classes/System/Solr/RequestFactory.php
  Classes/System/Solr/Service/AbstractSolrService.php
  Classes/System/Solr/SolrConnection.php
  Configuration/SiteConfiguration/Overrides/sites.php
  Documentation/Configuration/Index.rst
  Documentation/Configuration/Reference/SolrConnection.rst
  Documentation/Configuration/Reference/TxSolrSolr.rst
  Documentation/GettingStarted/ConfigureExtension.rst
  Documentation/Images/GettingStarted/LegacySiteMode_extension_settings.jpg
  Documentation/Images/GettingStarted/Site_handling_Setup_solr_01.jpg
  Documentation/Images/GettingStarted/Site_handling_Setup_solr_01.png
  Resources/Private/Php/ComposerLibraries/composer.json
  Resources/Private/Php/ComposerLibraries/composer.lock
  Tests/Integration/IntegrationTest.php
  Tests/Integration/System/Solr/Fixtures/SolrConnectionTest_slim_basic_sites.xml
  Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
  Tests/Integration/System/Solr/Service/SolrWriteServiceTest.php
  Tests/Integration/System/Solr/SolrConnectionTest.php
  Tests/Unit/ConnectionManagerTest.php
  Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
  Tests/Unit/Search/RelevanceComponentTest.php
  Tests/Unit/System/Solr/Service/SolrAdminServiceTest.php
  Tests/Unit/System/Solr/SolrConnectionTest.php
  composer.json
Labels: enhancement, task

#2901 [BUGFIX] Use Iconfactory to retrieve record icons
  Classes/Backend/IndexingConfigurationSelectorField.php
Labels: BACKPORTABLE, PORTED
