Repository TYPO3-Solr/ext-solr, pull requests merged in 2021-04, with the labels that each got.

#2841 [BUGFIX] Language aspect for indexer
  Classes/IndexQueue/Indexer.php
Labels: BACKPORTABLE, bug

#2883 [BUGFIX:BP:11] Language aspect for indexer
  Classes/IndexQueue/Indexer.php
Labels: bug

#2917 [BUGFIX] remove escaping on suggestion prefix
  Classes/Controller/SuggestController.php
  Classes/Domain/Search/Query/SuggestQuery.php
  Tests/Integration/Controller/Fixtures/can_suggest_with_uri_special_chars.xml
  Tests/Integration/Controller/SuggestControllerTest.php
Labels: BACKPORTABLE
