Repository TYPO3-Solr/ext-solr, pull requests merged in 2021-01, with the labels that each got.

#2827 [BUGFIX:BACKPORT:10] Quote field within score calculation
  Classes/Domain/Search/Score/ScoreCalculationService.php
Labels: 10LTS, bug

#2826 [BUGFIX:BACKPORT:11] Quote field within score calculation
  Classes/Domain/Search/Score/ScoreCalculationService.php
Labels: 11LTS, bug

#2825 [BUGFIX] Quote field within score calculation
  Classes/Domain/Search/Score/ScoreCalculationService.php
Labels: BACKPORTABLE

#2796 [BUGFIX] disabled Solr Sites #2795
  Classes/Domain/Site/Site.php
  Classes/Domain/Site/SiteInterface.php
  Classes/Domain/Site/SiteRepository.php
  Tests/Integration/Domain/Site/Fixtures/get_available_sites_do_not_return_sites_not_enabled.xml
  Tests/Integration/Domain/Site/SiteRepositoryTest.php
  Tests/Integration/IntegrationTest.php
  Tests/Unit/Domain/Site/SiteRepositoryTest.php
Labels: BACKPORTABLE

#2833 [TASK] Disable cache time information for ajax request
  Configuration/TypoScript/Examples/Suggest/setup.typoscript
Labels: BACKPORTABLE
